import registeredThemes from './siteThemes.json';

export interface SiteTheme {
  // The value placed on the page wrapper. Site SCSS uses it to scope its rules.
  name: string;
  // Browser path to the CSS generated by styles:sites:build.
  stylesheet: string;
}

// The creation command updates JSON data without rewriting this lookup code.
const siteThemes: Readonly<Record<string, SiteTheme>> = registeredThemes;

export function getSiteTheme(siteName?: string): SiteTheme | undefined {
  // Do not apply one site's design to an unknown site as a fallback.
  if (!siteName || !Object.hasOwn(siteThemes, siteName)) return undefined;
  return siteThemes[siteName];
}
