export interface SiteTheme {
  // The value placed on the page wrapper. Site SCSS uses it to scope its rules.
  name: string;
  // Browser path to the CSS generated by styles:sites:build.
  stylesheet: string;
}

// Keys are actual CMS site names, not page names or partial design names.
// Register site themes on the development branch with their matching SCSS files.
// demo-site is a reference theme. It is only loaded for that exact CMS site name.
const siteThemes: Readonly<Record<string, SiteTheme>> = {
  'demo-site': {
    name: 'demo-site',
    stylesheet: '/Sites/demo-site/styles/main.css',
  },
};

export function getSiteTheme(siteName?: string): SiteTheme | undefined {
  // Do not apply one site's design to an unknown site as a fallback.
  if (!siteName || !Object.hasOwn(siteThemes, siteName)) return undefined;
  return siteThemes[siteName];
}
